Все задания рекомендуется выполнять вручную, проверяя полученные результаты с использованием NumPy.

__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [145]:
import numpy as np

def find_minor(matrix, index):
    minor = []
    data = matrix[1:]
    for row in data:
        minor_raw = []
        for i, elem in enumerate(row):
            if i != index:
                minor_raw.append(elem)
        minor.append(minor_raw)
    return np.asarray(minor)
    
def find_det_3d(matrix):
    start_count = 1
    det = 0
    for i in range(3):
        minor_i = find_minor(matrix, i)
        det += start_count * find_det(minor_i) * matrix[0][i]
        start_count *= -1
        
    return det
        
        
def find_det(matrix):
    det = matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    return det


In [146]:
matrix = np.asarray([[4,2,3],[0,5,1], [0,0,9]])

In [147]:
find_det_3d(matrix), np.linalg.det(matrix)

(180, 180.0)

In [148]:
x = 1
matrix = np.asarray([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])
find_det(matrix)

1.0

In [149]:
matrix = np.asarray([[1,2,3],[4,5,6],[7,8,9]])
find_det_3d(matrix), np.linalg.det(matrix)

(0, 0.0)

__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

In [150]:
A = [[], [], []]
detA = 4
detAA = detA * detA
defAt = detA
det2A = np.power(2, len(A)) * detA

In [151]:
matrix = np.asarray([[-2,7,-3],[4,-14,6],[-3,7,13]])
find_det_3d(matrix)

0

In [152]:
def find_rank(matrix):
    rank = min(matrix.shape) + 1
    m_shape = matrix.shape
    det = 0
    while det == 0:
        rank -=1
        for i in range(m_shape[0]-rank + 1):
            for j in range(m_shape[1]-rank + 1):
                calc_matrix = matrix[i:i+rank, j:j+rank]
                calc_det = np.linalg.det(calc_matrix)
                if calc_det != 0:
                    det = calc_det
    return rank

In [153]:
matrix = np.asarray([[1,2,3],[1,1,1],[2,3,4]])

In [154]:
find_rank(matrix), np.linalg.matrix_rank(matrix)

(2, 2)

In [155]:
matrix = np.asarray([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])

In [156]:
find_rank(matrix), np.linalg.matrix_rank(matrix)

(3, 3)

Все задания рекомендуется делать вручную, проверяя полученные результаты через NumPy.

__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    
__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

__5*.__ Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [163]:
A = np.ones((4,2))
B = np.random.rand(4,2)

In [168]:
np.dot(A, B)

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [169]:
np.dot(B, A)

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [170]:
A = np.ones((2,5))
B = np.ones((5,3))

In [172]:
np.dot(A,B).shape

(2, 3)

In [173]:
np.dot(B,A)

ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

In [174]:
A = np.ones((8,3))
B = np.ones((3,8))

In [175]:
np.dot(A,B).shape

(8, 8)

In [177]:
np.dot(B,A).shape

(3, 3)

In [178]:
A = np.ones((4,4))
B = np.ones((4,4))

In [179]:
np.dot(A,B).shape

(4, 4)

In [180]:
np.dot(B,A).shape

(4, 4)

In [181]:
A = np.asarray([[1, -2],[3, 0]])
B = np.asarray([[4,-1],[0, 5]])

In [182]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [183]:
np.dot(A,B)

array([[  4, -11],
       [ 12,  -3]])

In [184]:
A = np.asarray([[1, 7],[3, -6]])
B = np.asarray([[0,5],[2, -1]])
C = np.asarray([[2, -4],[1, 1]])

In [185]:
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

In [186]:
A = np.asarray([[4, 1],[5, -2],[2,3]])

In [187]:
At = A.transpose()

In [189]:
np.dot(At, A)

array([[45,  0],
       [ 0, 14]])

In [190]:
np.dot(A,At)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])